"""Deterministic seeder producing a realistic Sri Lankan dataset.

Run with::

    python -m app.seed.seeder --reset

Everything is generated from a fixed RNG seed so the demo is reproducible.
All patients, doctors and facilities are fictional.
"""

from __future__ import annotations

import argparse
import random
import sys
from datetime import date, datetime, time, timedelta, timezone

import bcrypt
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.clinical.catalog import (
    CAPABILITY_BY_CODE,
    DIAGNOSTIC_TESTS,
    SPECIALTIES,
    SPECIALTY_BY_CODE,
)
from app.core.db import SessionLocal, create_all, engine
from app.models import (
    Appointment,
    CareEnrollment,
    CareProgramme,
    Consultation,
    DailyCheckIn,
    DiagnosticTest,
    Doctor,
    DoctorSchedule,
    ElderlyRecord,
    FacilityCapability,
    FacilityTestOffering,
    GuardianAlert,
    GuardianPermission,
    GuardianRelationship,
    Hospital,
    MaternalRecord,
    Medication,
    MedicationLog,
    Notification,
    PatientProfile,
    Referral,
    Specialty,
    SystemConfig,
    User,
    VitalRecord,
)
from app.models.enums import (
    AlertSeverity,
    AppointmentStatus,
    CheckInType,
    ConsultationStatus,
    EnrollmentStatus,
    FacilityType,
    GuardianPermissionType,
    Language,
    MedicationLogStatus,
    NotificationCategory,
    NotificationPriority,
    ProgrammeType,
    ReferralStatus,
    Sex,
    UrgencyLevel,
    UserRole,
    VerificationStatus,
    VisitType,
    WellbeingStatus,
)
from app.seed import reference as ref

RNG_SEED = 20260807
DEMO_PASSWORD = "Demo@1234"

# Volume targets (spec §22).
#
# N_APP_PATIENTS is the 300 fully-profiled SuwaPath app users the spec calls
# for. N_PATIENTS is larger because appointments are generated by walking real
# doctor schedules: 70 doctors at realistic clinic utilisation produce tens of
# thousands of visits over the history window, and attributing those to only
# 300 people would give every patient hundreds of appointments a year. The
# extra records represent the hospitals' wider patient base, and keep both
# utilisation and per-patient visit counts realistic.
N_APP_PATIENTS = 300
N_PATIENTS = 3000
N_DOCTORS = 70
N_DIAGNOSTIC_CENTRES = 10
N_HOSPITAL_ADMINS = 20
N_GUARDIAN_LINKS = 120
N_CONSULTATIONS = 300

# Care-programme cohorts are capped so the demo stays fast; they are sampled
# from the eligible population rather than enrolling everyone.
N_MATERNAL_CASES = 40
N_POSTPARTUM_CASES = 18
N_ELDERLY_CASES = 60
N_MEDICATION_PATIENTS = 300

rng = random.Random(RNG_SEED)

# bcrypt is deliberately slow; every seeded account shares one demo password, so
# the hash is computed once rather than 400+ times.
_SHARED_HASH: str | None = None


def shared_password_hash() -> str:
    global _SHARED_HASH
    if _SHARED_HASH is None:
        _SHARED_HASH = bcrypt.hashpw(
            DEMO_PASSWORD.encode("utf-8"), bcrypt.gensalt(rounds=10)
        ).decode("utf-8")
    return _SHARED_HASH


def utc(dt: datetime) -> datetime:
    return dt.replace(tzinfo=timezone.utc) if dt.tzinfo is None else dt


def log(message: str) -> None:
    print(f"  {message}", flush=True)


# --------------------------------------------------------------------------
# Name generation
# --------------------------------------------------------------------------
def make_name(sex: Sex, ethnicity: str | None = None) -> str:
    ethnicity = ethnicity or rng.choices(
        ["sinhala", "tamil", "muslim", "burgher"], weights=[0.70, 0.16, 0.10, 0.04]
    )[0]

    if ethnicity == "tamil":
        first = rng.choice(
            ref.TAMIL_FEMALE_FIRST if sex == Sex.FEMALE else ref.TAMIL_MALE_FIRST
        )
        return f"{first} {rng.choice(ref.TAMIL_SURNAMES)}"
    if ethnicity == "muslim":
        first = rng.choice(
            ref.MUSLIM_FEMALE_FIRST if sex == Sex.FEMALE else ref.MUSLIM_MALE_FIRST
        )
        return f"{first} {rng.choice(ref.MUSLIM_SURNAMES)}"
    if ethnicity == "burgher":
        first = rng.choice(
            ref.SINHALA_FEMALE_FIRST if sex == Sex.FEMALE else ref.SINHALA_MALE_FIRST
        )
        return f"{first} {rng.choice(ref.BURGHER_SURNAMES)}"

    first = rng.choice(
        ref.SINHALA_FEMALE_FIRST if sex == Sex.FEMALE else ref.SINHALA_MALE_FIRST
    )
    return f"{first} {rng.choice(ref.SINHALA_SURNAMES)}"


_used_emails: set[str] = set()


def make_email(full_name: str, domain: str = "example.lk") -> str:
    base = full_name.lower().replace(" ", ".").replace("'", "")
    candidate = f"{base}@{domain}"
    counter = 2
    while candidate in _used_emails:
        candidate = f"{base}{counter}@{domain}"
        counter += 1
    _used_emails.add(candidate)
    return candidate


def make_phone() -> str:
    return f"+947{rng.choice('01245678')}{rng.randint(1000000, 9999999)}"


def jitter_location(loc: ref.Location, spread: float = 0.035) -> tuple[float, float]:
    """Scatter a person around a city centre so distances vary realistically."""
    return (
        round(loc.latitude + rng.uniform(-spread, spread), 6),
        round(loc.longitude + rng.uniform(-spread, spread), 6),
    )


def weighted_location() -> ref.Location:
    return rng.choices(ref.LOCATIONS, weights=[l.population_weight for l in ref.LOCATIONS])[0]


# --------------------------------------------------------------------------
# Reset
# --------------------------------------------------------------------------
def reset_database(db: Session) -> None:
    log("Truncating existing data...")
    tables = [
        "guardian_alerts", "hospital_alerts", "notifications", "messages",
        "no_show_predictions", "forecasts", "audit_logs",
        "daily_check_ins", "vital_records", "medication_logs", "medications",
        "maternal_records", "elderly_records", "care_enrollments",
        "referrals", "consultations", "appointments",
        "image_analyses", "medical_images", "extracted_values",
        "extracted_reports", "medical_documents",
        "recommendations", "red_flag_assessments", "structured_intakes",
        "symptom_messages", "symptom_sessions", "anonymous_health_sessions",
        "facility_test_offerings", "doctor_schedules", "doctors",
        "patient_profiles", "guardian_permissions", "guardian_relationships",
        "facility_capabilities", "diagnostic_tests", "care_programmes",
        "system_configs", "users", "hospitals", "specialties",
    ]
    db.execute(text(f"TRUNCATE {', '.join(tables)} RESTART IDENTITY CASCADE"))
    db.commit()


# --------------------------------------------------------------------------
# Catalogues
# --------------------------------------------------------------------------
def seed_specialties(db: Session) -> dict[str, Specialty]:
    out: dict[str, Specialty] = {}
    for spec in SPECIALTIES:
        row = Specialty(
            code=spec.code,
            name=spec.name,
            name_si=spec.name_si,
            name_ta=spec.name_ta,
            description=spec.description,
            keywords=spec.keywords,
            sub_specialties=spec.sub_specialties,
        )
        db.add(row)
        out[spec.code] = row
    db.flush()
    log(f"Specialties: {len(out)}")
    return out


def seed_tests(db: Session) -> dict[str, DiagnosticTest]:
    out: dict[str, DiagnosticTest] = {}
    for test in DIAGNOSTIC_TESTS:
        row = DiagnosticTest(
            code=test.code,
            name=test.name,
            category=test.category,
            description=test.description,
            required_capability=test.required_capability,
            typical_price_lkr=test.price_lkr,
            preparation_notes=test.preparation,
        )
        db.add(row)
        out[test.code] = row
    db.flush()
    log(f"Diagnostic tests: {len(out)}")
    return out


def seed_facilities(
    db: Session, tests: dict[str, DiagnosticTest]
) -> tuple[list[Hospital], list[Hospital]]:
    hospitals: list[Hospital] = []
    centres: list[Hospital] = []

    def build(seed: ref.HospitalSeed, facility_type: FacilityType) -> Hospital:
        loc = ref.LOCATION_BY_CITY[seed.city]
        lat, lon = jitter_location(loc, spread=0.02)
        hospital = Hospital(
            name=seed.name,
            facility_type=facility_type,
            registration_no=f"MOH/{rng.randint(1000, 9999)}/{rng.randint(10, 99)}",
            city=loc.city,
            district=loc.district,
            address=f"{rng.randint(1, 340)}, {rng.choice(['Main Street', 'Hospital Road', 'Temple Road', 'Station Road', 'Galle Road', 'Lake Drive'])}, {loc.city}",
            latitude=lat,
            longitude=lon,
            phone=f"+9411{rng.randint(2000000, 5999999)}",
            email=f"info@{seed.name.split()[0].lower()}.lk",
            opening_time=None if seed.is_24_hours else time(7, 0),
            closing_time=None if seed.is_24_hours else time(21, 0),
            is_24_hours=seed.is_24_hours,
            has_emergency=seed.has_emergency,
            bed_count=seed.beds,
            icu_bed_count=seed.icu_beds,
            consultation_rooms=seed.consultation_rooms,
            verification_status=VerificationStatus.VERIFIED,
            rating=round(rng.uniform(3.8, 4.8), 1),
        )
        db.add(hospital)
        db.flush()

        for code in seed.capabilities:
            cap = CAPABILITY_BY_CODE.get(code)
            if not cap:
                continue
            db.add(
                FacilityCapability(
                    hospital_id=hospital.id,
                    capability_code=cap.code,
                    capability_name=cap.name,
                    category=cap.category,
                    is_available=True,
                )
            )

        # Offer every test this facility has the capability to run.
        available = set(seed.capabilities)
        for test in DIAGNOSTIC_TESTS:
            if test.required_capability in available:
                db.add(
                    FacilityTestOffering(
                        hospital_id=hospital.id,
                        test_id=tests[test.code].id,
                        price_lkr=round(test.price_lkr * rng.uniform(0.85, 1.25), -1),
                        turnaround_hours=rng.choice([4, 8, 12, 24, 48]),
                    )
                )
        return hospital

    for seed in ref.HOSPITALS:
        hospitals.append(build(seed, FacilityType.HOSPITAL))
    for seed in ref.DIAGNOSTIC_CENTRES:
        centres.append(build(seed, FacilityType.DIAGNOSTIC_CENTRE))

    db.flush()
    log(f"Hospitals: {len(hospitals)}, diagnostic centres: {len(centres)}")
    return hospitals, centres


def seed_care_programmes(db: Session) -> dict[str, CareProgramme]:
    programmes = [
        CareProgramme(
            code="maternal_care",
            name="Maternal & Postpartum Care",
            programme_type=ProgrammeType.MATERNAL,
            description=(
                "Pregnancy monitoring, antenatal visit reminders, warning-sign "
                "check-ins and postpartum recovery support."
            ),
            milestones=[
                {"week": 12, "label": "First trimester scan", "test": "usg_obstetric"},
                {"week": 20, "label": "Anomaly scan", "test": "usg_obstetric"},
                {"week": 26, "label": "Glucose tolerance test", "test": "fbs"},
                {"week": 28, "label": "Third trimester review", "test": "cbc"},
                {"week": 34, "label": "Growth scan", "test": "usg_obstetric"},
                {"week": 38, "label": "Pre-delivery assessment", "test": None},
            ],
            check_in_questions=MATERNAL_QUESTIONS,
            default_reminders=[
                {"code": "anc_visit", "label": "Antenatal visit", "offset_days": -2},
                {"code": "supplements", "label": "Iron & folic acid", "time": "20:00"},
            ],
        ),
        CareProgramme(
            code="postpartum_care",
            name="Postpartum & Newborn Care",
            programme_type=ProgrammeType.POSTPARTUM,
            description=(
                "Maternal recovery, feeding support, mental-wellbeing screening "
                "and newborn follow-up including vaccination reminders."
            ),
            milestones=[
                {"day": 3, "label": "Newborn first review", "test": None},
                {"day": 7, "label": "Maternal recovery check", "test": None},
                {"day": 42, "label": "Six-week postnatal review", "test": None},
                {"day": 60, "label": "Newborn vaccination (BCG/OPV)", "test": None},
            ],
            check_in_questions=POSTPARTUM_QUESTIONS,
            default_reminders=[
                {"code": "newborn_vaccine", "label": "Newborn vaccination", "offset_days": -3},
            ],
        ),
        CareProgramme(
            code="elderly_care",
            name="Elderly Care",
            programme_type=ProgrammeType.ELDERLY,
            description=(
                "Simplified daily check-ins, medication confirmation, vitals "
                "tracking and consent-based guardian alerts."
            ),
            milestones=[
                {"month": 1, "label": "Monthly medication review", "test": None},
                {"month": 3, "label": "Quarterly bloods", "test": "cbc"},
                {"month": 6, "label": "Six-month clinical review", "test": "lipid_profile"},
            ],
            check_in_questions=ELDERLY_QUESTIONS,
            default_reminders=[
                {"code": "daily_checkin", "label": "Daily check-in", "time": "09:00"},
            ],
        ),
        CareProgramme(
            code="sexual_health",
            name="Confidential Sexual Health",
            programme_type=ProgrammeType.SEXUAL_HEALTH,
            description=(
                "Private guidance, confidential STI testing recommendations and "
                "discreet provider matching."
            ),
            milestones=[],
            check_in_questions=[],
            default_reminders=[],
        ),
    ]
    for programme in programmes:
        db.add(programme)
    db.flush()
    log(f"Care programmes: {len(programmes)}")
    return {p.code: p for p in programmes}


MATERNAL_QUESTIONS = [
    {"code": "severe_headache", "label": "Severe headache?", "danger": True},
    {"code": "blurred_vision", "label": "Blurred vision or seeing spots?", "danger": True},
    {"code": "vaginal_bleeding", "label": "Any bleeding?", "danger": True},
    {"code": "severe_abdominal_pain", "label": "Severe abdominal pain?", "danger": True},
    {"code": "reduced_fetal_movement", "label": "Reduced baby movement?", "danger": True},
    {"code": "leaking_fluid", "label": "Any fluid leaking?", "danger": True},
    {"code": "swelling", "label": "Sudden swelling of face or hands?", "danger": True},
    {"code": "fever", "label": "Fever?", "danger": True},
    {"code": "feeling_well", "label": "Are you feeling well overall?", "danger": False},
]

POSTPARTUM_QUESTIONS = [
    {"code": "severe_bleeding", "label": "Heavy bleeding (soaking a pad in an hour)?", "danger": True},
    {"code": "fever", "label": "Fever or chills?", "danger": True},
    {"code": "severe_headache", "label": "Severe headache?", "danger": True},
    {"code": "low_mood", "label": "Feeling persistently low or unable to cope?", "danger": True},
    {"code": "child_not_feeding", "label": "Is the baby feeding poorly?", "danger": True},
    {"code": "feeding_going_well", "label": "Is feeding going well?", "danger": False},
]

ELDERLY_QUESTIONS = [
    {"code": "wellbeing", "label": "How are you feeling today?", "danger": False},
    {"code": "pain", "label": "Any pain today?", "danger": False},
    {"code": "dizziness", "label": "Feeling dizzy or unsteady?", "danger": True},
    {"code": "injury", "label": "Have you had a fall?", "danger": True},
    {"code": "shortness_of_breath", "label": "Any breathing difficulty?", "danger": True},
    {"code": "chest_pain", "label": "Any chest pain?", "danger": True},
]


def seed_system_config(db: Session) -> None:
    configs = [
        SystemConfig(
            key="ai.orchestrator",
            category="ai",
            description="Gemini orchestration settings",
            value={
                "provider": "gemini",
                "model": "gemini-2.0-flash",
                "temperature": 0.2,
                "max_follow_up_questions": 6,
                "fallback": "deterministic_rule_engine",
            },
        ),
        SystemConfig(
            key="ai.red_flag_engine",
            category="clinical",
            description="Deterministic clinical rule layer",
            value={"version": "1.0.0", "llm_may_override": False},
        ),
        SystemConfig(
            key="cv.adapters",
            category="ai",
            description="Registered computer-vision model adapters",
            value={
                "chest_xray": {"adapter": "pneumonia", "enabled": True},
                "skin_lesion": {"adapter": "dermatology", "enabled": False},
            },
        ),
        SystemConfig(
            key="matching.weights",
            category="matching",
            description="Provider ranking factor weights",
            value={
                "specialty": 30, "availability": 18, "capability": 16,
                "distance": 14, "urgency_fit": 12, "sub_specialty": 8,
                "language": 7, "consultation_mode": 5, "experience": 5,
                "verification": 4,
            },
        ),
        SystemConfig(
            key="notifications.reminders",
            category="notifications",
            description="Reminder lead times in hours",
            value={"appointment": [48, 24, 2], "medication": [0], "anc_visit": [72, 24]},
        ),
    ]
    for config in configs:
        db.add(config)
    db.flush()
    log(f"System configs: {len(configs)}")


# --------------------------------------------------------------------------
# Notifications and guardian alerts
# --------------------------------------------------------------------------
def seed_notifications(
    db: Session,
    appointments: list[Appointment],
    demo: dict[str, User],
    care_data: dict[str, list],
) -> int:
    """In-app notifications across every category (spec §21)."""
    now = datetime.now(timezone.utc)
    notifications: list[Notification] = []

    # Appointment reminders for upcoming bookings.
    upcoming = [
        a for a in appointments
        if a.scheduled_start > now and a.status in
        (AppointmentStatus.CONFIRMED, AppointmentStatus.PENDING)
    ]
    for appointment in upcoming[:220]:
        hours_away = (appointment.scheduled_start - now).total_seconds() / 3600
        when = appointment.scheduled_start.strftime("%I:%M %p").lstrip("0")
        day_label = (
            "tomorrow"
            if hours_away < 48
            else appointment.scheduled_start.strftime("on %d %b")
        )
        notifications.append(
            Notification(
                user_id=appointment.patient_user_id,
                category=NotificationCategory.APPOINTMENT,
                priority=(
                    NotificationPriority.HIGH if hours_away < 48
                    else NotificationPriority.NORMAL
                ),
                title="Upcoming appointment",
                body=f"Your appointment is {day_label} at {when}.",
                action_type="appointment",
                action_id=appointment.id,
                is_read=rng.random() < 0.4,
                scheduled_for=appointment.scheduled_start - timedelta(days=1),
            )
        )

    # Maternal programme reminders.
    for record in care_data["maternal"][:60]:
        if record.is_postpartum:
            notifications.append(
                Notification(
                    user_id=record.patient_user_id,
                    category=NotificationCategory.CARE_PROGRAMME,
                    priority=NotificationPriority.NORMAL,
                    title="Newborn vaccination due",
                    body="Your baby's next vaccination is due in 3 days.",
                    action_type="care_programme",
                    action_id=record.enrollment_id,
                )
            )
        else:
            week = record.pregnancy_week or 0
            notifications.append(
                Notification(
                    user_id=record.patient_user_id,
                    category=NotificationCategory.CARE_PROGRAMME,
                    priority=NotificationPriority.NORMAL,
                    title="Antenatal visit approaching",
                    body=f"You are at week {week}. Your next antenatal visit is in 2 days.",
                    action_type="care_programme",
                    action_id=record.enrollment_id,
                )
            )

    # Medication reminder for the elderly demo persona.
    notifications.append(
        Notification(
            user_id=demo["elderly"].id,
            category=NotificationCategory.MEDICATION,
            priority=NotificationPriority.HIGH,
            title="Medication due",
            body="Time to take Amlodipine 5mg (1 tablet, after breakfast).",
            action_type="medication",
        )
    )

    db.add_all(notifications)
    db.flush()
    log(f"Notifications: {len(notifications)}")
    return len(notifications)


def seed_guardian_alerts(db: Session, demo: dict[str, User]) -> int:
    """Pattern-based guardian alerts for the demo guardian.

    Only alert types the patient has consented to are created (rule 6). The
    maternal dependent has not granted REPORTS, so no report alert is created
    for her.
    """
    guardian = db.query(User).filter(User.email == "guardian@suwapath.lk").one()
    now = datetime.now(timezone.utc)

    alerts = [
        GuardianAlert(
            patient_user_id=demo["elderly"].id,
            guardian_user_id=guardian.id,
            alert_type="missed_medication_pattern",
            severity=AlertSeverity.CRITICAL,
            title="Repeated missed medication",
            detail=(
                "Sunil has missed 3 consecutive doses of Amlodipine 5mg. "
                "This is a blood-pressure medication marked as critical."
            ),
            required_permission=str(GuardianPermissionType.MEDICATIONS),
            meta={"medication": "Amlodipine 5mg", "consecutive_missed": 3},
        ),
        GuardianAlert(
            patient_user_id=demo["elderly"].id,
            guardian_user_id=guardian.id,
            alert_type="missed_checkin_pattern",
            severity=AlertSeverity.ATTENTION,
            title="Daily check-ins missed",
            detail="Sunil has not completed a daily check-in for 3 days.",
            required_permission=str(GuardianPermissionType.WELLBEING),
            meta={"consecutive_missed": 3},
        ),
        GuardianAlert(
            patient_user_id=demo["elderly"].id,
            guardian_user_id=guardian.id,
            alert_type="abnormal_vitals",
            severity=AlertSeverity.ATTENTION,
            title="Raised blood pressure recorded",
            detail="A reading of 158/94 mmHg was recorded, above the usual range.",
            required_permission=str(GuardianPermissionType.WELLBEING),
            meta={"systolic": 158, "diastolic": 94},
        ),
        GuardianAlert(
            patient_user_id=demo["maternal"].id,
            guardian_user_id=guardian.id,
            alert_type="appointment_upcoming",
            severity=AlertSeverity.INFO,
            title="Antenatal visit in 2 days",
            detail="Dilini has an antenatal appointment scheduled in 2 days.",
            required_permission=str(GuardianPermissionType.APPOINTMENTS),
        ),
    ]
    db.add_all(alerts)

    for alert in alerts:
        db.add(
            Notification(
                user_id=guardian.id,
                category=NotificationCategory.GUARDIAN_ALERT,
                priority=(
                    NotificationPriority.CRITICAL
                    if alert.severity == AlertSeverity.CRITICAL
                    else NotificationPriority.NORMAL
                ),
                title=alert.title,
                body=alert.detail,
                about_patient_user_id=alert.patient_user_id,
                action_type="guardian_alert",
            )
        )

    db.flush()
    log(f"Guardian alerts: {len(alerts)}")
    return len(alerts)


# --------------------------------------------------------------------------
# Orchestration
# --------------------------------------------------------------------------
def seed_all(db: Session, *, reset: bool = False) -> None:
    from app.seed import journeys, people

    if reset:
        reset_database(db)

    print("\nSeeding SuwaPath dataset...")
    password_hash = shared_password_hash()

    specialties = seed_specialties(db)
    tests = seed_tests(db)
    hospitals, centres = seed_facilities(db, tests)
    programmes = seed_care_programmes(db)
    seed_system_config(db)

    system_admin, hospital_admins = people.seed_admins(db, rng, password_hash, hospitals)
    log(f"Admins: 1 system + {len(hospital_admins)} hospital")

    doctors = people.seed_doctors(db, rng, password_hash, hospitals, specialties)
    log(f"Doctors: {len(doctors)}")

    patients, demo = people.seed_patients(db, rng, password_hash)
    log(f"Patients: {len(patients)}")

    profiles = {
        p.user_id: p
        for p in db.query(PatientProfile).all()
    }

    guardians = people.seed_guardians(db, rng, password_hash, patients, profiles, demo)
    relationship_count = db.query(GuardianRelationship).count()
    log(f"Guardians: {len(guardians)} users, {relationship_count} relationships")

    db.commit()

    hospitals_by_id = {h.id: h for h in hospitals + centres}
    doctors_by_id = {d.id: d for d in doctors}

    appointments = journeys.seed_appointments(
        db, rng, patients, profiles, doctors, hospitals_by_id
    )
    upcoming = sum(
        1 for a in appointments
        if a.scheduled_start >= datetime.now(timezone.utc)
    )
    log(f"Appointments: {len(appointments)} ({len(appointments) - upcoming} historical, {upcoming} upcoming)")

    consultations = journeys.seed_consultations(
        db, rng, appointments, doctors_by_id, limit=N_CONSULTATIONS
    )
    log(f"Consultations: {len(consultations)}")

    referrals = journeys.seed_referrals(db, rng, consultations, doctors, hospitals)
    log(f"Referrals: {len(referrals)}")

    db.commit()

    care_data = journeys.seed_care_programmes_data(
        db, rng, patients, profiles, programmes, doctors, hospitals, demo
    )
    log(
        f"Care enrolments: {len(care_data['enrollments'])} "
        f"({len(care_data['maternal'])} maternal, {len(care_data['elderly'])} elderly)"
    )

    medications, med_logs = journeys.seed_medications(
        db, rng, patients, profiles, doctors, demo
    )
    log(f"Medications: {len(medications)} with {len(med_logs)} dose records")

    check_ins, vitals = journeys.seed_check_ins_and_vitals(db, rng, care_data, demo)
    log(f"Check-ins: {len(check_ins)}, vitals: {len(vitals)}")

    db.commit()

    seed_notifications(db, appointments, demo, care_data)
    seed_guardian_alerts(db, demo)
    db.commit()

    print("\nDemo accounts (password for all: Demo@1234)")
    print("  patient@suwapath.lk    Nimali Fernando   — patient")
    print("  maternal@suwapath.lk   Dilini Fernando   — patient, 28wk pregnant")
    print("  elderly@suwapath.lk    Sunil Fernando    — patient, elderly care")
    print("  guardian@suwapath.lk   Nimal Fernando    — guardian of both above")
    print("  doctor@suwapath.lk     Dr. Dileepa Perera — endocrinologist")
    print("  hospital@suwapath.lk   Chathurika Bandara — hospital admin")
    print("  admin@suwapath.lk      Ravindu Wickramasinghe — system admin")
    print("\nSeeding complete.\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Seed the SuwaPath database")
    parser.add_argument(
        "--reset", action="store_true", help="Truncate existing data before seeding"
    )
    args = parser.parse_args()

    create_all()
    db = SessionLocal()
    try:
        seed_all(db, reset=args.reset)
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
